spring:
  application:
    name: hzero-swagger
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_governance?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}

feign:
  hystrix:
    enabled: true

hystrix:
  stream:
    queue:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: ${HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS:90000}

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

choerodon:
  eureka:
    event:
      retry-time: 30
      retry-interval: 10
      skip-services: zipkin**, **gateway**, **register**, **oauth**

hzero:
  swagger:
    client: ${HZERO_SWAGGER_CLIENT:client}
    oauth-url: ${HZERO_OAUTH_URL:http://dev.hzero.org:8080/oauth/oauth/authorize}
    skip-service: ${HZERO_SWAGGER_SKIP_SERVICE:hzero-register, hzero-gateway, hzero-gateway-helper, hzero-oauth}
    gateway-domain: ${HZERO_GATEWAY_DOMAIN:dev.hzero.org:8080}
    fetch-time: ${HZERO_SWAGGER_FETCH_TIME:20}
    fetch-seconds: ${HZERO_SWAGGER_FETCH_SECONDS:30}

logging:
  level:
    org.apache.ibatis: ${LOG_LEVEL:info}
    org.hzero: ${LOG_LEVEL:info}
    org.springframework.web: ${LOG_LEVEL:info}

